### ISSUE TITLE
not detecting libjemalloc.so.2 on recent distributions?

### ISSUE THREAD

**Issue by ntavares** [centminmod/centminmod-sysbench#1]
Hi guys,

Thanks for sharing this script. Just to let you know that on CentOS-8, the jemalloc is not .so.1 anymore:
```
sh-4.4# cat /etc/redhat-release 
CentOS Linux release 8.1.1911 (Core) 
sh-4.4# rpm -qa | grep jemalloc
jemalloc-5.2.1-2.el8.x86_64
sh-4.4# rpm -ql jemalloc | grep lib64
/usr/lib64/libjemalloc.so.2
```

**Comment by centminmod** [comment]
Thanks for the heads up, have fixed it in this commit https://github.com/centminmod/centminmod-sysbench/commit/ce8cd91efacc48d621929449cc8bdb680e634fa6 :)
